//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public string Adress { get; set; }
        public Nullable<int> ID_Parent { get; set; }
        public Nullable<int> ID_Group { get; set; }
        public Nullable<int> Gender { get; set; }
    
        public virtual Gender Gender1 { get; set; }
        public virtual Group Group { get; set; }
        public virtual Parent Parent { get; set; }
    }
}
